/* eslint-disable */
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.nl.toefel.trains.GetTrackLayoutResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.nl.toefel.trains.InfraComponent');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nl.toefel.trains.GetTrackLayoutResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nl.toefel.trains.GetTrackLayoutResponse.repeatedFields_, null);
};
goog.inherits(proto.nl.toefel.trains.GetTrackLayoutResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.nl.toefel.trains.GetTrackLayoutResponse.displayName = 'proto.nl.toefel.trains.GetTrackLayoutResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nl.toefel.trains.GetTrackLayoutResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nl.toefel.trains.GetTrackLayoutResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    width: jspb.Message.getFieldWithDefault(msg, 1, 0),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0),
    componentsList: jspb.Message.toObjectList(msg.getComponentsList(),
    proto.nl.toefel.trains.InfraComponent.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nl.toefel.trains.GetTrackLayoutResponse}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nl.toefel.trains.GetTrackLayoutResponse;
  return proto.nl.toefel.trains.GetTrackLayoutResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nl.toefel.trains.GetTrackLayoutResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nl.toefel.trains.GetTrackLayoutResponse}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 3:
      var value = new proto.nl.toefel.trains.InfraComponent;
      reader.readMessage(value,proto.nl.toefel.trains.InfraComponent.deserializeBinaryFromReader);
      msg.addComponents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nl.toefel.trains.GetTrackLayoutResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nl.toefel.trains.GetTrackLayoutResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getComponentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.nl.toefel.trains.InfraComponent.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 width = 1;
 * @return {number}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.setWidth = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 height = 2;
 * @return {number}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.setHeight = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated InfraComponent components = 3;
 * @return {!Array<!proto.nl.toefel.trains.InfraComponent>}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.getComponentsList = function() {
  return /** @type{!Array<!proto.nl.toefel.trains.InfraComponent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.nl.toefel.trains.InfraComponent, 3));
};


/** @param {!Array<!proto.nl.toefel.trains.InfraComponent>} value */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.setComponentsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.nl.toefel.trains.InfraComponent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nl.toefel.trains.InfraComponent}
 */
proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.addComponents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.nl.toefel.trains.InfraComponent, opt_index);
};


proto.nl.toefel.trains.GetTrackLayoutResponse.prototype.clearComponentsList = function() {
  this.setComponentsList([]);
};


